# Generated by Django 3.0.4 on 2020-04-05 12:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOutageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 4, 5, 15, 56, 22, 887216))),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='serviceoutagerecord',
            constraint=models.UniqueConstraint(fields=('service_id', 'duration', 'start_time'), name='unique_service_record'),
        ),
    ]
