# Generated by Django 3.0.4 on 2021-12-22 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service_outages', '0002_load_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoutagerecord',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 11, 7, 37, 186914, tzinfo=utc)),
        ),
    ]
